[package]
name = "hplt_minhash_retrieval"
version = "0.1.0"
edition = "2024"
authors = ["Étienne Simon <esimon@esimon.eu>"]
description = "Find documents inside HPLT v4"

[dependencies]
clap = { version = "4.5", features = ["derive", "string"] }
fnv = "1.0"
gaoya = "0.2"
regex = "1.12"
serde_json = "1.0"
zstd-framed = "0.1"
